create table public.cad_resposta (
    id bigint generated by default as identity not null,
    created_at timestamp with time zone not null default now(),
    rseq smallint not null default '1'::smallint,
    descricao text not null,
    constraint resposta_pkey primary key (id)
) TABLESPACE pg_default;