create table public.pergunta (
    id integer generated by default as identity not null,
    qid integer not null,
    created_at timestamp with time zone not null default now(),
    nome text not null,
    descricao text null,
    tipo public.tipo_pergunta not null default 'card'::tipo_pergunta,
    pseq smallint not null default '1'::smallint,
    template text not null default 'Frequência'::text,
    constraint pergunta_pkey primary key (id)
) TABLESPACE pg_default;