create table public.qalternativa (
    id bigint generated by default as identity not null,
    created_at timestamp with time zone not null default now(),
    pid integer not null,
    rid integer not null,
    seq smallint null,
    score smallint null default '0'::smallint,
    img text null default 'blob:https://bggenerator.com/394d828a-3a2a-41e9-a131-fc22309ef531'::text,
    constraint rpergunta_pkey primary key (id)
) TABLESPACE pg_default;