create table public.questionario (
    id integer generated by default as identity not null,
    created_at timestamp with time zone not null default now(),
    nome character varying not null,
    descricao character varying not null,
    img text null,
    constraint questionario_pkey primary key (id)
) TABLESPACE pg_default;