create table public.template (
    id bigint generated by default as identity not null,
    created_at timestamp with time zone not null default now(),
    nome text not null,
    rid integer not null,
    constraint Template_pkey primary key (id),
    constraint template_rid_fkey foreign KEY (rid) references cad_resposta (id)
) TABLESPACE pg_default;